trigger:
- releases/*

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: sh BuildExecutables.sh
  displayName: 'Build and create executables'

- task: CopyFiles@2
  displayName: 'Copy executables to staging directory'
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)/tmp'
    Contents: 'protocol-builder*'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'  

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifacts'
  inputs:
    PathtoPublish: $(Build.ArtifactStagingDirectory)
    ArtifactName: executables
