trigger:
  branches:
    include:
    - refs/tags/v*

pool:
  vmImage: 'ubuntu-latest'

steps:
- powershell: |
   $gitTag = "$(Build.SourceBranch)" -replace '(.*)/tags/(.+)', '$2'
   Write-Host "##vso[task.setvariable variable=gitTag]$gitTag"
   
  displayName: 'Extract git tag'

- task: Docker@2
  displayName: buildAndPush
  inputs:
    containerRegistry: 'rhythmicode_docker_hub'
    repository: 'rhythmicode/protocol-builder'
    Dockerfile: '**/Dockerfile'
    buildContext: '**'
    tags: |
     $(gitTag)
     latest

- script: sh BuildExecutables.sh
  displayName: 'Build and create executables'

- task: CopyFiles@2
  displayName: 'Copy executables to staging directory'
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)/tmp'
    Contents: 'protocol-builder*'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'  

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifacts'
  inputs:
    PathtoPublish: $(Build.ArtifactStagingDirectory)
    ArtifactName: executables
