trigger:
- releases/*

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: sh BuildExecutables.sh
  displayName: 'Build and create executable'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: $(Build.ArtifactStagingDirectory)/tmp/protocol-builder*
    ArtifactName: binaries
