trigger:
  branches:
    include:
    - refs/tags/v*

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'rhythmicode_docker_hub'
    repository: 'rhythmicode/protocol-builder'
    command: 'buildAndPush'
    Dockerfile: './Dockerfile'
    buildContext: '.'
    tags: |
      $(Build.BuildNumber)
      latests

- script: sh BuildExecutables.sh
  displayName: 'Build and create executables'

- task: CopyFiles@2
  displayName: 'Copy executables to staging directory'
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)/tmp'
    Contents: 'protocol-builder*'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'  

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifacts'
  inputs:
    PathtoPublish: $(Build.ArtifactStagingDirectory)
    ArtifactName: executables
